import { useWalletModal } from '@solana/wallet-adapter-react-ui';
import type { NextPage } from 'next';
import Head from 'next/head';
import ConnectButton from '../components/ConnectButton';

const Home: NextPage = () => {
  const { visible, setVisible } = useWalletModal();

  return (
    <div>
      <Head>
        <title>Gamify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>main</div>
        <ConnectButton />
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
